name: Black

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Run black
        run: black SaitamaRobot
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automated code formatting
          title: Format code.
          body: Automated code formatting.
          labels: ⚫️ black
          branch: autofix
          committer: Ryomen-Sukuna<80420642+Ryomen-Sukuna@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          delete-branch: true
